import type { OrphixIconTheme } from "../../types";

export const orphixDefaultIcons: OrphixIconTheme = {
  id: "orphix.default.icons",
  themeId: "orphix",
  variantId: "default",

  name: "Orphix Default Icons",

  icons: {
    meta: {
      style: "outline",
      defaultSize: "md",
      sizes: {
        xs: 14,
        sm: 16,
        md: 18,
        lg: 22,
        xl: 26,
      },
      stroke: {
        thin: 1,
        regular: 1.5,
        medium: 2,
        bold: 2.5,
      },
      radius: "round",
    },
    core: {
      app: "orb",
      terminal: "terminal",
      command: "command",
      settings: "settings",
      search: "search",
      close: "x",
      add: "plus",
      remove: "minus",
      split: "split-square-horizontal",
      splitHorizontal: "split-square-horizontal",
      splitVertical: "split-square-vertical",
      maximize: "maximize",
      minimize: "minimize",
      restore: "panel-top",
      refresh: "refresh-cw",
      more: "ellipsis",
      chevronRight: "chevron-right",
      chevronDown: "chevron-down",
      externalLink: "external-link",
      copy: "copy",
      check: "check",
    },
    panels: {
      workspace: "folder-kanban",
      files: "files",
      agents: "bot",
      extensions: "blocks",
      settings: "settings",
      terminal: "terminal",
      search: "search",
    },
    files: {
      file: "file",
      folder: "folder",
      folderOpen: "folder-open",
      typescript: "file-type",
      javascript: "file-code",
      react: "atom",
      rust: "settings-2",
      python: "file-code",
      go: "file-code",
      json: "braces",
      markdown: "file-text",
      css: "palette",
      html: "code-xml",
      image: "image",
      lock: "lock",
      config: "settings-2",
      package: "package",
      docker: "container",
      git: "git-branch",
      unknown: "file-question",
    },
    agents: {
      agent: "bot",
      agentRunning: "circle-play",
      agentIdle: "circle",
      agentError: "circle-alert",
      agentPaused: "circle-pause",
    },
    status: {
      success: "circle-check",
      warning: "triangle-alert",
      danger: "circle-x",
      info: "info",
      loading: "loader-circle",
    },
  },
};
