import type { OrphixIconTheme } from "../../types";

export const orphixMinimalIcons: OrphixIconTheme = {
  id: "orphix.minimal.icons",
  themeId: "orphix",
  variantId: "minimal",

  name: "Orphix Minimal Icons",

  icons: {
    meta: {
      style: "minimal",
      defaultSize: "md",
      sizes: {
        xs: 14,
        sm: 16,
        md: 18,
        lg: 22,
        xl: 26,
      },
      stroke: {
        thin: 1,
        regular: 1.5,
        medium: 2,
        bold: 2.5,
      },
    },
    core: {
      app: "circle",
      terminal: "chevron-right",
      command: "hash",
      settings: "sliders-horizontal",
      search: "search",
      close: "x",
      add: "plus",
      remove: "minus",
      split: "columns-2",
      splitHorizontal: "columns-2",
      splitVertical: "rows-2",
      maximize: "maximize",
      minimize: "minimize",
      restore: "panel-top",
      refresh: "refresh-cw",
      more: "more-horizontal",
      chevronRight: "chevron-right",
      chevronDown: "chevron-down",
      externalLink: "arrow-up-right",
      copy: "clipboard",
      check: "check",
    },
    panels: {
      workspace: "layout-grid",
      files: "file",
      agents: "cpu",
      extensions: "puzzle",
      settings: "sliders-horizontal",
      terminal: "chevron-right",
      search: "search",
    },
    files: {
      file: "file",
      folder: "folder",
      folderOpen: "folder-open",
      typescript: "file",
      javascript: "file",
      react: "file",
      rust: "file",
      python: "file",
      go: "file",
      json: "file",
      markdown: "file",
      css: "file",
      html: "file",
      image: "file",
      lock: "file",
      config: "file",
      package: "file",
      docker: "file",
      git: "git-branch",
      unknown: "file",
    },
    agents: {
      agent: "cpu",
      agentRunning: "play",
      agentIdle: "circle",
      agentError: "alert-triangle",
      agentPaused: "pause",
    },
    status: {
      success: "check",
      warning: "alert-triangle",
      danger: "x",
      info: "info",
      loading: "loader",
    },
  },
};
