import type { OrphixIconTheme } from "../../types";

export const orphixRoundedIcons: OrphixIconTheme = {
  id: "orphix.rounded.icons",
  themeId: "orphix",
  variantId: "rounded",

  name: "Orphix Rounded Icons",

  icons: {
    meta: {
      style: "rounded",
      defaultSize: "md",
      sizes: {
        xs: 14,
        sm: 16,
        md: 18,
        lg: 22,
        xl: 26,
      },
      stroke: {
        thin: 1,
        regular: 1.5,
        medium: 2,
        bold: 2.5,
      },
      radius: "full",
    },
    core: {
      app: "circle",
      terminal: "terminal",
      command: "command",
      settings: "settings",
      search: "search",
      close: "x-circle",
      add: "plus-circle",
      remove: "minus-circle",
      split: "split-square-horizontal",
      splitHorizontal: "split-square-horizontal",
      splitVertical: "split-square-vertical",
      maximize: "maximize-2",
      minimize: "minimize-2",
      restore: "panel-top",
      refresh: "refresh-cw",
      more: "more-horizontal",
      chevronRight: "chevron-right-circle",
      chevronDown: "chevron-down-circle",
      externalLink: "external-link",
      copy: "copy",
      check: "check-circle",
    },
    panels: {
      workspace: "folder-kanban",
      files: "files",
      agents: "bot",
      extensions: "blocks",
      settings: "settings",
      terminal: "terminal",
      search: "search",
    },
    files: {
      file: "file",
      folder: "folder",
      folderOpen: "folder-open",
      typescript: "file-type",
      javascript: "file-code",
      react: "atom",
      rust: "settings-2",
      python: "file-code",
      go: "file-code",
      json: "braces",
      markdown: "file-text",
      css: "palette",
      html: "code-xml",
      image: "image",
      lock: "lock",
      config: "settings-2",
      package: "package",
      docker: "container",
      git: "git-branch",
      unknown: "file-question",
    },
    agents: {
      agent: "bot",
      agentRunning: "circle-play",
      agentIdle: "circle",
      agentError: "circle-alert",
      agentPaused: "circle-pause",
    },
    status: {
      success: "circle-check",
      warning: "triangle-alert",
      danger: "circle-x",
      info: "info",
      loading: "loader-circle",
    },
  },
};
